backend:
    name: git-gateway
    branch: main
local_backend: true
media_folder: public/img
public_folder: img
collections:
    - name: 'settings'
      label: 'Settings'
      files:
          - label: 'Site settings'
            name: 'settings'
            file: 'content/settings.md'
            fields:
                - { label: 'Site title', name: 'site_title', widget: 'string' }
                - {
                      label: 'Site description',
                      name: 'site_description',
                      widget: 'text',
                  }
                - {
                      label: 'Homepage',
                      name: 'homepage',
                      widget: 'relation',
                      collection: 'pages',
                      search_fields: ['title'],
                      value_field: ['title', 'date', 'body'],
                  }
    - name: 'pages'
      label: 'Pages'
      folder: 'content/pages'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'projects'
      label: 'Projects'
      folder: 'content/projects'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Link', name: 'link', required: false, widget: 'string' }
          - {
                label: 'Github link',
                name: 'github_link',
                required: false,
                widget: 'string',
            }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - {
                label: 'Featured Image',
                name: 'thumbnail',
                required: false,
                widget: 'image',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
